package main

import (
	"bufio"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPart1(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`
	scanner := bufio.NewScanner(strings.NewReader(input))
	expected := 14
	assert.Equal(t, expected, part1(scanner))
}

func TestPart2(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`
	scanner := bufio.NewScanner(strings.NewReader(input))
	expected := 34
	assert.Equal(t, expected, part2(scanner))
}
